# Generated by Django 4.1.7 on 2023-04-01 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userpreference',
            table='preference',
        ),
    ]
